version: '3'
services:
  api:
    build:
      context: ./api
    ports:
      - "7000:7000"
    command: uvicorn --reload --workers 1 --host 0.0.0.0 --port 7000 app.app:app
    volumes:
      - ./api/app:/opt/api/app
      - ./api/tests:/opt/api/tests
